### ISSUE TITLE
Unable to create tag from relation

### ISSUE THREAD

**Issue by noxify** [rinvex/tag#12]
Hi,

while running my seeders, I got a validation error:

In my seeder, i have the following:

```
$lesson = App\Models\Lesson::create([
					'user_id'   => 1,
					'title'     => $faker->text(70),
					'content'   => $faker->realText(100, true),
					'status'    => $faker->randomElement(['draft', 'published']),
					'type'      => $lesson_type
				]);
				
				$lesson->tag($faker->words(5));
```

`$faker->words(5)` returns an array, which should be valid (based on the readme).

I added a try/catch block to the seeder ( based on the readme from [dwightwatson/validating](https://github.com/dwightwatson/validating) ) 

The result is:

```
object(Illuminate\Support\MessageBag)#1538 (2) {
  ["messages":protected]=>
  array(1) {
    ["slug"]=>
    array(1) {
      [0]=>
      string(27) "The slug field is required."
    }
  }
  ["format":protected]=>
  string(8) ":message"
}

```

I created also an Seeder for the Tags to see, what's going wrong without all of my own stuff:

```
<?php

use Rinvex\Tag\Tag;
use Illuminate\Database\Seeder;

class TagTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    $faker = Faker\Factory::create();
	
	    $tags = $faker->words(1);
	    
	    foreach ($tags as $tag) {
		    
	    	    //works fine, if slug is defined
			    Tag::create([
				    'name' => $tag,
				    'slug' => str_slug($tag),
				    'description' => $tag
			    ]);
			    
			    //doesn't work
			    //Tag::createByName($tag);
			    
		    } catch (Watson\Validating\ValidationException $e) {
			    $errors = $e->getErrors();
			    var_dump($errors);
		    }
	    	
	    }
    }
}
```

Did I miss something?

Thanks :)

* MAMP PRO with PHP 7.1.0
* OSX
* Postgres
* Tag develop branch

**Comment by Omranic** [comment]
Yeah, issue confirmed. Seems that rules validation happens before slug auto creation, which results a validation error. Hmmm, how could we solve this efficiently.. 🤔  Let's see..

**Comment by Omranic** [comment]
I really appreciate this bug report @noxify, it was affecting four of our packages actually, and it's been fixed now on all through the **dev-develop** branches. Enjoy the new release 😉

**Comment by noxify** [comment]
Tested it currently with my seeds (without the workaround) and everything works fine.

thanks @Omranic
